
const allFacts = [
  "Before age of 6 lived in Portugal, Spain, Kenya, Egypt, and Japan.",
  "At peak Britney, Dorton and I got handed free tickets to Britney Spears. We didn't know where the tickets were and asked the owner. He was all, 'Are you serious? Down in the front row.' FRONT ROW.",
  "Has spent a night in Jail. The most valuable part of being in Jail is having a blanket. Some have 5. I had 0.",
  "Was a t-swift fan before it was conventionally accepted as OK for a 30 something male to do so.",
  "In 2015, the Wo family was flown to NYC to participate in a marketing photo shoot as the Talent for an ad campaign. Being paid, this made JWo a PROFESSIONAL MODEL.",
  " I was like THISCLOSE last year to getting a TIY regional-conference held on the river (not near. on). I mean what could go wrong? just float down the river and discuss code.",
  "TIY has been thought to be a bar, a ship-yard, and a school teaching people how to work on railroads. By state regulators.",
  " I would absolutely want to go to that bar/ship-and-rail-yard/school. In that order.",
  "I have a t-shirt for a honkytonk near houston, Gilleys, that is supposedly worth like $80. Gilley's was the place in 1980s Urban Cowboy.",
  "When teaching a cohort I don't re-wear tshirts. So, I have to remember which shirts I've worn for those 60 days and set them aside.",
  "you can take jwo away from the river but you can't take the river away from jwo.",
  "8 year olds don't know that Justin Timberlake was even in a boy band; they just seen him as an actor who sometimes sings sometimes. So yeah, let that sink in.",
  "Dorton is literally last person I know not on facebook. My wife's parents? recently on it.  Banker friend who held out? now on it. Dorton? says its a fad.",
  "FUNFACT™ Sooo, Matt KEAS and I flew to Greenville in February 2014 to interview and hang out with the then very small TIY team. When landing into GVL, it was pitch black and raining with hella-turbulance. No me gusta. The pilot pulled out of the landing and flew to atlanta and landed and said, We'll try again in 30 minutes. NOPE. nopenopenope. We got off that plane.  Matt rented a car and we drove up to GVL. best.decision.ever.",
  "I had a fun-fact all written out about how the brontosaurus isn’t REALLY a dinosaur (true story, all kids learn how it’s apatosaurus, not brontosaurus), but then read in wikipedia that in 2015 some paleontologist said NO WAIT REALLY it IS REALLY a dinosaur after all, sorry about all those books written from 1990->2015. but then OTHER paleontologists are like talk-to-the-hand, and so now some people will only do “Brontosaurus” like with the quotes. Unsure if air-quotes are used in person tho.",
  "since you're in Dallas, I bet growing up whenever you met someone from out of town, they'd ask you if you rode a horse to school. Never failed; California, Florida, Pennsylvania: everybody convinced that every single kid in Texas rode a horse to school. There's even a facebook page[0] with 22,000 likes named 'Yea, im from Texas; no i dont ride a horse to school.' However, I don't know where this comes from because the only time I ever rode a horse was in Colorado[1] AND I just read a story how someone DID ride a horse to school and was suspended[2]!  Soo... do you ride a horse to TIY?",
  "FunFact™ literally my favorite joke about JavaScript is to confuse Java with it. Do I mean actual literal 'literally' or only the common-tongue figurative literal? No one knows! It's sort of like the word 'ironic', which was immortalized 21 years ago in Ironic. Alanis Morissette may or may not have used the word 'ironic' ironically, but one thing is for sure known: the things in her song are literally not ironic. But still, I wouldn't wish 10,000 spoons on someone when all they need is a knife. That's just rude.",
  " My mom was born in The Twin Cities … she said she never ever ever wanted to live in the snow again. So we settled in Texas. Where it doesn't snow. Ever. Like seriously, my kids have never seen snow. I remember the one time it snowed in Houston; it was 1995. We have 2 seasons: summer, and not-quite-summer. So yeah, right now I dislike walking outside for more than 15 seconds. But talk to me in January. #summerforeva",
  "FunFact™ I was totes typing in “The TIY” which is of course ridiculous. there’s a podcast I love, The History of Rome, or THOR, but I see it referred to as The THOR podcast, which is just like, weird, man. Speaking of rome though, your fair city of Cincy is named after Cincinnatus, the roman dictator who gave us his dictator powers in the BCs. Which, btw, is why George Washington was compared to Cincinnatus for doing the same a two millennia later. this has been The TFF series (The Fun Fact). Welcome!",
  "welcome to The DC campus! You know what's just about the opposite of DC? Oregon. And you get there via the Oregon Trail, which just about everyone may age loves to joke about. So much so that instead of millennilol vs gen-X, there's a distinct subset of people where if you mention dysentery, they totally know you're talking about Oregon Trail. (The Oregon Trail Generation). There's also now choose your own adventure style books (also from my era) that cover the Oregon Trail, and I TOTALLY got there the first time and my son choose poorly and died of hunger after selling his ox for food. Rookie mistake.",
  "FUNFACT: a skipper is a baseball manager. Now, this itself isn't fun, but you know what is? TIY :heart::baseball:.  Example: the Durham team has outings at the Durham Bull stadium, and the Greenville Red Sox stadium has an entire outfield thing that is super awesome. I grew up watching Nolan pitch in the Astros, which was awesome. Now, if you don't like baseball, I can also provide a FUNFACT on skipping, but mostly that's movement that should decide  already between walking and running i mean common.",
  "FUNFACT: After college, we traveled to new orleans for Jazz Fest (because, obvs, right after college), and stayed with a guy named JJ. Now, JJ Watt has two named that start with J, hence JJ. But, this JJ in NO for jazz-fest, he was just named JJ. Like, on the birth certificate, 'JJ'. Which, I would have been all, “What’s the J stand for?” -> “J”. What about the other J?” -> “J”. note: this funfact puts the FUN in funfact more than all other funfacts because jazz fest is on point.",
  " I tried to understand @jim’s Minnesota Karma Train. I failed.  badly. It’s like that time that my friends in highschool told me I was going to WallyWorld! I was so excited. Then, after we left Walmart, I was like, “where’s wally world?!”. But you see, walmart IS wallyworld and I didn’t know. Just like I don’t know what VikingRunningFishTwinDuckPrince means.",
  "FunFact™ in 2007, people began linking to YouTube videos with Rick Astley's Never Gonna Give You Up in the middle, this Rick rolling them. It's been viewed 70 million times, and Astley made $12. Pretty lucrative! So yeah, you need a video of you rolling (literally or figuratively) and you'd be Rick Rolling.",
  "FUNFACT™ most people say godfather is their favorite (and/or best) gangster movie. And they're not wrong, but that's more a movie about a dad about 3 sons. (Seen described as King and 3 princes). Anyway, Goodfellas is awesome in its own right (this is known). Why bring this up? Because of the funniness that is all kids in the neighborhood being named Paul because of Paulie. Always loved that",
  "FUNFACT™ An intern is defined as 'One who is interned', which I feel is a turrble definition. Instead, I like to think of it as increasing the badassery one day at a time.  So each day, as you’re designing allthethings (making the logo bigger), you can be all, “I just interned the hell out of that Marcom poster of @jasonstrand”, or, as you print off color tshirts, you can tell the tshirt, “YOU JUST GOT INTERNED”. welcome!",
  "One of my favorite ice breakers is to ask which saturday kids show you identify most with as a kid. Example: mine is clearly Saved By The Bell. Only on for like 4 years (though it did have the terrible 8th grade and the summer episodes which ruled). And we’re going to agree to not talk about SBTB College. However, we could talk about the Wedding in Las Vegas if you really want to. So, which are you?",
  "FUNFACT™ In highschool, Katy Highschool was (and is) pretty good at TX highschool football. They killed us. Later I learned that Katy was named for the Missouri–Kansas–Texas railroad. (M-K-T -> Katy). Welcome!",
  "FUNFACT™ I'm not a designer, but I did buy the 'Stop Stealing Sheep' book in the 90's and have purchased so many fonts. SO MANY FONTS Ashley. So yeah, I have powers: I can basically tell when something is designed and when it's forsure100not. So your wizard-like spells confound me and my meager muggle abilities to make something NotEmbarassing™. That's the bar to which I hold my students: NotEmbarassing™.  This works well in everyday life too: “Well, my finances aren’t what you’d call brag-worthy, but it’s NotEmbarassing™… This brisket just needs some ketchup, it’s [EDITORS NOTE this is not OK]”",
  "FUNFACT™ For a certain age group who do not live in Durham, I believe the first thing people think about when you say 'Durham' is 'Bull Durham'. BD is reported by some as the best baseball movie of all time, which is nonsense.  It might (MIGHT) be the best kevin costner baseball movie of all time but the thing is, all costner baseball movies are romantic comedies. You want a real baseball movie? Give me The Natural ever day of the week.",
  "FUNFACT™ twitter was all twittering this weekend about two comedians getting engaged. The proposer tweeted “.@proposee :ring:”. Did you either propose or get proposed to on social media? Well, I should ask: “on which social media site were you engaged? I got married before Facebook was Facebook, so I had to ask AWo on friendster*. * based on a true story * in which AWo and JWo did get engaged but not on social media",
  "FUNFACT™ On the Wo roadtrip 2015 (houston to SLC), we played golf in salt lake city on a mountain. which: STRONG. But not as strong as I felt hitting the loaner clubs. I was like, man THESE clubs are what I need, not my old-busted-af clubs that are at least 6 years old. But then, before hitting buy-now, @dorton was all, “so it was the elevation, huh?” … me: :sadpanda: but yeah. So, if you want to play golf well, go to SLC!",
  "FUNFACT™ There’s a popular’ish theory that the Rock of the late 80’s (let’s call that Detroit) became very produced, leading directly to the Grunge movement in the early nineties (call that Seattle). I distinctly remember buying cassettes from the Detroit era and CDs in the Seattle era. Poof, casettes were gone (except for mix tapes, which lived on as actual physical tapes you would give someone until you could burn CDs in the early aughts). TODAY there’s a store in brooklyn (obvs) selling only cassettes. I’d have to imagine the tapes skew closer to your town than the west coast.",
  "FUNFACT™ B2B reminds me of the 1990’s. Everything was Clinton, eyeballs, and marketplaces. I joined promoorder.com (later changed to promorder when dot coms fell out of favor). All we needed was 1% of every transaction of a 6Billion business. It didn’t quite work out the way we thought. Nowadays you have to move to Portland to live out the dream of the nineties",
  "FUNFACT™ my parentals and I visited london in 1996 for a spring break trip. It was a crazy amount of awesome. Nearly 20 years later, I listened to History of Rome, which SO HIGHLY RECOMMEND. Anyhow, once AD 43 rolled around, we learned all about Londinium. Me: “I wonder which settlement became London?”. Now, I had a better explanation for not knowing what became Paris, because it was Lutetia Parisiorum but only ever called it Lutetia. But Londinium? Should have probably known that. tldr; Londinium => London.",
  "FUNFACT™ James Taylor’s “Carolina on my Mind” is the unofficial anthem of both North Carolinas and my heart. If I ever achieve peak-jwo-accoustic-guitar I’ll play James Taylor like he played James Taylor. James Ryan Taylor, both @dorton and my bff, goes by Ryan Taylor and while he has played guitar in the past, he is of no relation to James Taylor (Guitarist).",
  "FUNFACT™ You’ll see the texas flag everywhere. Seriously. It’s the only state that a) joined as a country via a treaty and b) likes to fly our flag at the same height as the US flag. So you’ll see far more dual-flag-poles than single-flag-poles.",
  "FunFact™ you can now watch The OC *legally* online. Also, it only aired 4 seasons, which I'm positive you're surprised at. It feels like 7 or 8 seasons easy, like HIMYM. Marissa, Obvs, was only in 3 seasons.",
  "Halloween is basically parents buying other parents candy, using their children as unwitting candy mules. This year, the Wos netted positive returns on candygate.",
  "FUNFACT™ in highschool, 1997 (OMG I AM SO OLD) I went to see Cary Pierce (of Jackopierce) in dallas. A group of 12 of us drove up there. Being 18 and all, it never entered my mind that we couldn’t see him play. At a 21 and up bar. at 18. But we were pretty goodkids and they let us in anyway after Cary saw us and let us in. Note that I do not bring up the Houston v Dallas rivalry. Even though [REDACTED]",
  "FUNFACT™ When in nashville, Jack (then 5yo now 7yo)  sang at The Oprey. he was all, I want to sing Story of Us, by Taylor Swift because obvs. The guy running the recording studio there was all, “ummm wut” and then after Jack nailed it, he was all, “woah”. Anyway, it was awesome and Nashville was charming as all get out.",
  "FUNFACT™ London Fog wasn’t natural fog at all, it was pollution. It’s like how Foster’s beer is not sold in australia. Which: I’m still a bit mad at.",
  "FUNFACT™ there was this article on Facebook about the 20 cheapest places to live. Obvs, plenty of :texas:  on there, but the pic was very familiar. I was all, whaaaaaaa, that’s greenville (it was the river with the rocks). And it was. As they seem to yes, “yeah, THAT greenville",
  "Welcome! FunFact™ : San Antonio has he world’s largest cowboy bots. My friend Jennifer Martinson’s dad mad them, so basically I was involved",
  " FUNFACT™ My buddy from college-times founded and runs the Ranger Creek distillery and brewery in San Antonio",
  "Fun fact: I have a 7 wolf howling shirt. It's peak-howl."
]

module.exports = {
  randomFact: function(){
    const index = Math.floor(Math.random() * allFacts.length);
    return allFacts[index];
  },
  allFacts: allFacts
}
